/* =============================================
   PG FINDER CHENNAI — DATA LAYER
   All PG listings, areas, testimonials
   ============================================= */

const PG_DATA = [
  {
    id: 1,
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&q=80",
    name: "Sri Lakshmi Residency",
    area: "Anna Nagar",
    address: "14th Main Road, Anna Nagar West, Chennai",
    price: 7500,
    gender: "Female",
    rating: 4.9,
    reviews: 42,
    emoji: "🏠",
    amenities: ["WiFi", "AC", "Food", "Laundry", "Security"],
    type: "Premium",
    available: true,
    phone: "9876543210",
    description: "Spacious, well-maintained PG for working women. Home-cooked meals, 24x7 security, and a warm homely atmosphere in the heart of Anna Nagar."
  },
  {
    id: 2,
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",
    name: "Comfort Stay PG",
    area: "T. Nagar",
    address: "Usman Road, T. Nagar, Chennai",
    price: 9000,
    gender: "Male",
    rating: 4.7,
    reviews: 35,
    emoji: "🏢",
    amenities: ["WiFi", "AC", "Gym", "Security", "TV"],
    type: "Premium",
    available: true,
    phone: "9876543211",
    description: "Modern PG for working professionals near T. Nagar bus stand. Close to Metro station and shopping areas."
  },
  {
    id: 3,
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80",
    name: "Ocean Breeze PG",
    area: "Adyar",
    address: "LB Road, Adyar, Chennai - 600020",
    price: 11000,
    gender: "Any",
    rating: 4.8,
    reviews: 58,
    emoji: "🌊",
    amenities: ["WiFi", "AC", "Food", "Parking", "Balcony"],
    type: "Premium",
    available: true,
    phone: "9876543212",
    description: "Premium PG minutes from the beach. Enjoy morning sea breeze, modern rooms, and a community of like-minded professionals."
  },
  {
    id: 4,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80",
    name: "Green Valley PG",
    area: "Velachery",
    address: "100 Feet Road, Velachery, Chennai",
    price: 5500,
    gender: "Any",
    rating: 4.6,
    reviews: 29,
    emoji: "🌿",
    amenities: ["WiFi", "Food", "TV", "Water 24x7"],
    type: "Budget",
    available: true,
    phone: "9876543213",
    description: "Affordable and clean PG near Velachery MRTS station. Perfect for students and early-career professionals."
  },
  {
    id: 5,
    image: "https://images.unsplash.com/photo-1626178793926-22b28830aa30?w=600&q=80",
    name: "Tech Hub PG",
    area: "OMR",
    address: "Perungudi, OMR, Chennai - 600096",
    price: 7000,
    gender: "Male",
    rating: 4.5,
    reviews: 47,
    emoji: "💻",
    amenities: ["WiFi", "AC", "Gym", "Shuttle", "Cafeteria"],
    type: "Standard",
    available: true,
    phone: "9876543214",
    description: "Designed for IT professionals on the OMR corridor. Office shuttle, high-speed WiFi, and a vibrant community."
  },
  {
    id: 6,
    image: "https://images.unsplash.com/photo-1543489822-c49534f3271f?w=600&q=80",
    name: "Lotus Residency",
    area: "Porur",
    address: "Near DLF, Porur, Chennai - 600116",
    price: 6500,
    gender: "Female",
    rating: 4.7,
    reviews: 33,
    emoji: "🌸",
    amenities: ["WiFi", "Food", "Laundry", "AC", "Security"],
    type: "Standard",
    available: true,
    phone: "9876543215",
    description: "Safe and secure PG for women near Porur IT Park. Round-the-clock security with a caring homeowner."
  },
  {
    id: 7,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80",
    name: "Heritage Home PG",
    area: "Mylapore",
    address: "Luz Church Road, Mylapore, Chennai",
    price: 8500,
    gender: "Any",
    rating: 4.8,
    reviews: 51,
    emoji: "🏛️",
    amenities: ["WiFi", "AC", "Food", "Temple Nearby", "Library"],
    type: "Premium",
    available: false,
    phone: "9876543216",
    description: "A heritage bungalow turned PG in cultural Mylapore. Serene environment, Kapaleeshwarar Temple walkable distance."
  },
  {
    id: 8,
    image: "https://images.unsplash.com/photo-1555636222-cae831e670b3?w=600&q=80",
    name: "Campus Stay PG",
    area: "Tambaram",
    address: "Tambaram East, Chennai - 600059",
    price: 4500,
    gender: "Male",
    rating: 4.4,
    reviews: 62,
    emoji: "🎓",
    amenities: ["WiFi", "Food", "Study Room", "TV"],
    type: "Budget",
    available: true,
    phone: "9876543217",
    description: "Most affordable student-friendly PG near Tambaram educational institutions. Study room available 24x7."
  },
  {
    id: 10,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80",
    name: "Royal Nest PG",
    area: "Guindy",
    address: "Near Guindy Industrial Estate, Guindy, Chennai - 600032",
    price: 6800,
    gender: "Male",
    rating: 4.6,
    reviews: 44,
    emoji: "👑",
    amenities: ["WiFi", "AC", "Food", "Gym", "Security"],
    type: "Standard",
    available: true,
    phone: "9876543219",
    description: "Well-equipped PG for professionals near Guindy Industrial Estate and SIDCO. Easy access to MRTS Guindy station and Anna University."
  },
  {
    id: 11,
    image: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=600&q=80",
    name: "Sunshine Ladies PG",
    area: "Kodambakkam",
    address: "Mettu Street, Kodambakkam, Chennai - 600024",
    price: 7200,
    gender: "Female",
    rating: 4.8,
    reviews: 39,
    emoji: "☀️",
    amenities: ["WiFi", "AC", "Food", "Laundry", "CCTV", "Security"],
    type: "Premium",
    available: true,
    phone: "9876543220",
    description: "Premium women-only PG in the heart of Kodambakkam. Close to film studios, hospitals, and shopping malls. 24x7 CCTV surveillance and strict security."
  },
  {
    id: 9,
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=600&q=80",
    name: "Skyline PG",
    area: "Sholinganallur",
    address: "Sholinganallur Junction, OMR, Chennai",
    price: 8000,
    gender: "Any",
    rating: 4.6,
    reviews: 38,
    emoji: "🌆",
    amenities: ["WiFi", "AC", "Rooftop", "Gym", "Security"],
    type: "Standard",
    available: true,
    phone: "9876543218",
    description: "Rooftop hangout area, modern amenities, and unbeatable OMR IT corridor access."
  }
];

const AREAS = [
  { name: "Anna Nagar",     count: 48,  emoji: "🌳", color: "#2FA896" },
  { name: "T. Nagar",       count: 62,  emoji: "🛍️", color: "#D4943A" },
  { name: "Velachery",      count: 55,  emoji: "🚉", color: "#D94F35" },
  { name: "OMR",            count: 87,  emoji: "💻", color: "#5A7FD4" },
  { name: "Adyar",          count: 39,  emoji: "🌊", color: "#2FA896" },
  { name: "Porur",          count: 31,  emoji: "🏭", color: "#D4943A" },
  { name: "Tambaram",       count: 44,  emoji: "🎓", color: "#D94F35" },
  { name: "Mylapore",       count: 27,  emoji: "🏛️", color: "#5A7FD4" },
  { name: "Sholinganallur", count: 53,  emoji: "🌆", color: "#2FA896" },
  { name: "Guindy",         count: 36,  emoji: "🏢", color: "#D4943A" },
  { name: "Kodambakkam",    count: 29,  emoji: "🎬", color: "#D94F35" },
  { name: "Chromepet",      count: 41,  emoji: "✈️", color: "#5A7FD4" },
];

const TESTIMONIALS = [
  {
    text: "Found my PG in just 2 days! The filters are super helpful and the owner details were accurate. Best platform for Chennai PG search.",
    name: "Priya R.",
    loc: "Software Engineer, OMR",
    rating: 5,
    initials: "PR"
  },
  {
    text: "As a student from Coimbatore, I was worried about finding a good PG in Chennai. This platform made it so easy — found a budget-friendly place near my college.",
    name: "Karthik S.",
    loc: "Student, Tambaram",
    rating: 5,
    initials: "KS"
  },
  {
    text: "The gender filter and verified listings gave me confidence as a solo woman. Highly recommended for female PG seekers in Chennai!",
    name: "Ananya M.",
    loc: "CA Professional, T. Nagar",
    rating: 5,
    initials: "AM"
  },
  {
    text: "Listed my PG here and got 6 enquiries in the first week. Great platform for PG owners too. Very responsive team.",
    name: "Ramesh V.",
    loc: "PG Owner, Anna Nagar",
    rating: 4,
    initials: "RV"
  },
  {
    text: "Clean UI, easy to use, and the area-wise listing helped me compare PGs quickly. Shifted to Chennai for a job and this saved me a lot of time.",
    name: "Deepika L.",
    loc: "Marketing Manager, Adyar",
    rating: 5,
    initials: "DL"
  },
  {
    text: "The WhatsApp enquiry button is genius — direct contact with owners, no middlemen. Found a great PG in Velachery within my budget.",
    name: "Sanjay N.",
    loc: "Data Analyst, Velachery",
    rating: 5,
    initials: "SN"
  }
];
